---
channel: beta
apps:
  cortex-stt:
    repository: hass-cortex/app-cortex-stt
    target: cortex-stt
    image: ghcr.io/hass-cortex/cortex_stt/{arch}
  cortex-tts:
    repository: hass-cortex/app-cortex-tts
    target: cortex-tts
    image: ghcr.io/hass-cortex/cortex_tts/{arch}
